name: loja_online_simples_flutter
description: Exemplo didático de loja online simples em Flutter e Dart para Android Studio.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  provider: ^6.0.7
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/products.json
    
    